apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: gangadhar369/flask-microservice:latest
          ports:
            - containerPort: 5000
          env:
            - name: SKIP_DB
              value: "true"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 20   # wait before first probe
            periodSeconds: 10         # check every 10s
            timeoutSeconds: 3
            failureThreshold: 5       # only fail if 5 checks fail
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 40   # wait longer before liveness kicks in
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
